import { Position, type Edge, type Node } from '@xyflow/react'

import { nanoid } from 'nanoid/non-secure'

export const initialNodes: Node[] = [
  {
    // id: nanoid(),
    id: '1',
    type: 'custom',
    data: { label: '1' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 0, y: 0 },
  },
  {
    // id: nanoid(),
    id: '2',
    type: 'custom',
    data: { label: '2' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 0, y: 300 },
  },
  {
    // id: nanoid(),
    id: '3',
    type: 'custom',
    data: { label: '3' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 0, y: 600 },
  },
  {
    // id: nanoid(),
    id: '1-1',
    type: 'custom',
    data: { label: '1-1' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 300, y: 0 },
    parentId: '1',
  },
  {
    // id: nanoid(),
    id: '1-2',
    type: 'custom',
    data: { label: '1-2' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 300, y: 100 },
    parentId: '1',
  },
  {
    // id: nanoid(),
    id: '2-1',
    type: 'custom',
    data: { label: '2-1' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 300, y: 0 },
    parentId: '2',
  },
  {
    // id: nanoid(),
    id: '2-1-1',
    type: 'custom',
    data: { label: '2-1-1' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 300, y: 0 },
    parentId: '2-1',
  },
  {
    // id: nanoid(),
    id: '3-1',
    type: 'custom',
    data: { label: '3-1' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 300, y: 0 },
    parentId: '3',
  },
  {
    // id: nanoid(),
    id: '3-2',
    type: 'custom',
    data: { label: '3-2' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 300, y: 100 },
    parentId: '3',
  },
  {
    // id: nanoid(),
    id: '3-3',
    type: 'custom',
    data: { label: '3-3' },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    position: { x: 300, y: 200 },
    parentId: '3',
  },
]

export const initialEdges: Edge[] = [
  {
    id: nanoid(),
    source: '1',
    target: '1-1',
    type: 'smoothstep',
  },
  {
    id: nanoid(),
    source: '1',
    target: '1-2',
    type: 'smoothstep',
  },
  {
    id: nanoid(),
    source: '2',
    target: '2-1',
    type: 'smoothstep',
  },
  {
    id: nanoid(),
    source: '2-1',
    target: '2-1-1',
    type: 'smoothstep',
  },
  {
    id: nanoid(),
    source: '3',
    target: '3-1',
    type: 'smoothstep',
  },
  {
    id: nanoid(),
    source: '3',
    target: '3-2',
    type: 'smoothstep',
  },
  {
    id: nanoid(),
    source: '3',
    target: '3-3',
    type: 'smoothstep',
  },
]
